http = "0.0.0.0:12345"

transfers = [
  "127.0.0.1:5821",
]

[logger]
    level = "info"
    format = "json"

[sender]
    type =  "n9e"
	concurrency = 20
	maxSamplePerBatch = 2000
	retryNum = 3
	timeout = 5


